go2_simulation:
  ros__parameters:
    Kp: 0.0 
    Kd: 0.0 
    compliance: 0.0
    material: "metal"
    horizon: 1000
    dt: 0.001
    tol: 0.000001
    tol_rel: 0.000001
    mu_prox: 0.0001
    maxit: 100
    warm_start: 1
    contact_solver: "ADMM"
    admm_update_rule: "spectral"
    max_patch_size: 4
    patch_tolerance: 0.001
